---
title: "15-minute cumulative opportunities map"
output: html_document
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(shiny)
library(tmap)
library(sf)
library(dplyr)
```

```{r, eval=FALSE, message=FALSE, echo=FALSE}
load("data/access_15.rda")
load("data/HAM_census_21.rda")
load("data/care_dest.rda")

access_15_DA <- access_15 |> group_by(from_id) |> summarise(GeoUID = first(GeoUID),
                                                            sum_copp_isc = sum(copp_isc),
                                                            sum_V_isc = sum(V_isc)) |> 
  group_by(GeoUID) |> summarise(med_copp_isc = median(sum_copp_isc, na.rm=T),
                                V_isc = sum(sum_V_isc, na.rm=T)) |>
  left_join(HAM_census_21, by="GeoUID") |> st_as_sf() |> st_make_valid()

save(access_15_DA, file="data/access_15_DA.rda")
```

```{r echo=FALSE, warning=FALSE, message=FALSE, results='hide'}
load("data/access_15_DA.rda")
load("data/care_dest.rda")
Community_Boundaries <- st_read("data/Boundaries/Community_Boundaries.shp", quiet = TRUE)
```

Median number of care destinations spatially accessible (by walk) within 15 mins from a parcel in each DA: 

```{r, echo=FALSE, warning=FALSE, message=FALSE}
tmap_mode("view")
tm_shape(access_15_DA) +
  tm_polygons("med_copp_isc",
              palette = c("darkred", "orange", "yellow", "green"),
              style = "quantile", n=4, alpha=0.3,
              border.alpha = 0.5,
              title = "Median # of care destinations (Quantiles)",
              legend.is.portrait = FALSE) +
  tm_shape(care_dest) +
  tm_dots(col = "Care_Category", palette = c("brown","blue","purple","green","cyan"))+
  tm_shape(Community_Boundaries) + tm_borders("black") + 
	tm_legend(outside=TRUE)
```

Population by DA:

```{r, echo=FALSE, warning=FALSE, message=FALSE}
tmap_mode("view")
tm_shape(access_15_DA) +
  tm_polygons("Population",
              palette = "Greens",
              style = "quantile", n=4, alpha=0.3,
              border.alpha = 0.5,
              title = "Population (Quantiles)",
              legend.is.portrait = FALSE) +
  tm_shape(care_dest) +
  tm_dots(col = "Care_Category", palette = c("brown","blue","purple","green","cyan"))+
  tm_shape(Community_Boundaries) + tm_borders("black") + 
	tm_legend(outside=TRUE)
```

Prevalence of low income based on the Low-income cut-offs, after tax (LICO-AT) (%):

```{r, echo=FALSE, warning=FALSE, message=FALSE}
tmap_mode("view")
tm_shape(access_15_DA |> rename("LICO-AT" = `v_CA21_1085: Prevalence of low income based on the Low-income cut-offs, after tax (LICO-AT) (%)`)) +
  tm_polygons("LICO-AT",
              palette = "Purples",
              style = "quantile", n=4, alpha=0.3,
              border.alpha = 0.5,
              title = "LICO-AT Prevelance (Quantiles)",
              legend.is.portrait = FALSE) +
  tm_shape(care_dest) +
  tm_dots(col = "Care_Category", palette = c("brown","blue","purple","green","cyan"))+
  tm_shape(Community_Boundaries) + tm_borders("black") + 
	tm_legend(outside=TRUE)
```